### ISSUE TITLE
question about tensor concat

### ISSUE THREAD

**Issue by makefile** [YixuanLi/densenet-tensorflow#10]
This code `l = tf.concat([c, l], 3)` in [this line](https://github.com/YixuanLi/densenet-tensorflow/blob/master/cifar10-densenet.py#L51) seems to be only concat the adjacent two layer output,
shouldn't it be to concat all previous layers in a dense block?

**Comment by YixuanLi** [comment]
In fact, when we concat two adjacent layers l_{i-1} and l_i, the concatenated layer would contain all previous layers since layer l_{i-1} already contains channels from l_1, l_2,...l_{i-2} already. It stacks accumulatively.
