### ISSUE TITLE
Weights initialization

### ISSUE THREAD

**Issue by ghost** [YixuanLi/densenet-tensorflow#12]
Hi, thanks for the beautiful code.

I'm just curious about the way you initialize the conv weights: 
    `tf.random_normal_initializer(stddev=np.sqrt(2.0/9/channel))`

Could you please explain a little bit about this setting? Because I found in the paper they 'adopt the weight initialization introduced by [10]', which is the MRSA initialization. Thanks in advance ;)

**Comment by ppwwyyxx** [comment]
This is the MSRA initialization for 3x3 conv.

**Comment by ghost** [comment]
Thanks a lot for your prompt reply. Now it makes sense to me. I didn't recognize this usage just now. Thanks again.

**Comment by cheerss** [comment]
As I know, MSRA take the number of input as its argument, namely, it should be std=np.sqrt(2/9/input_channel), but the 'channel' in your code represents the number of output channels, is it a typo?

**Comment by ppwwyyxx** [comment]
> As I know, MSRA take the number of input as its argument,

This is not true. Using input or output are both OK.
