### ISSUE TITLE
Results error

### ISSUE THREAD

**Issue by alicesue** [YixuanLi/densenet-tensorflow#8]
How to test the results? 
And how to plot the picture you showed?

**Comment by YixuanLi** [comment]
You don't need to perform test separately. There is already callback performing the test during the training process. See L150 in the main script.

You should be able to find a file summarizing all the training and test errors in 'train_log'.

**Comment by alicesue** [comment]
The val_error is the test error? Is it right?

**Comment by YixuanLi** [comment]
That's right
